### ISSUE TITLE
Allow echo commands to accept images and stickers in addition to text

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#12]
Right now an echo command is set via `/admin BOTNAME echo COMMANDNAME TEXT-TO-ECHO`, and that can be done in pieces by entering `/admin`, selecting a bot, selecting echo, typing just the command name, then typing the text to echo separately.

It would be nice if, following the long process, users could send the bot a sticker or image instead of just typing text, and the bot would send the sticker/image in response to a user typing the new command.

The admin module itself has something similar, where you can go into `/admin`, select a bot, select admin, then forward a message from another user rather than typing their numeric id. The ntelebot preprocessor converts forwarded messages into text messages that just contain the forwardee's userid:
```py
            if payload.get('forward_from'):
                text = '%s' % payload['forward_from']['id']
            else:
                text = payload.get('text', '')
```
so:
```
> /admin BOTNAME admin
> Forwarded from 12345:
  | Hello there
```
is treated as if the user typed:
```
> /admin BOTNAME admin
> 12345
```
which the conversation logic stitches back to `/admin BOTNAME admin 12345`. We could extend that logic in ntelebot to simply do the same for stickers and images, replacing them with their id codes, but it might be a little fragile to just guess that an all-numeric code is an int, a string with hyphens is an image, and otherwise is a sticker, or something along those lines. It might be worth having ntelebot actually emit the object type, possibly using `user:12345` for users, which metabot just strips, and `sticker:CAADAQ...` for stickers and `image:AgADA...` for images, which the echo module stores verbatim and converts into a sticker/image reply on the way out.

Alternatively, ntelebot could actually store the whole artifact in Context.data rather than appending something to Context.text. Then the admin module would have to look for either a target having been typed or an attached forwarded message, along the lines:
```py
-     target = ctx.text
+     if ctx.data and ctx.data['type'] == 'forwarded':
+         target = '%s' % ctx.data['forward_from']['id']
+     else:
+         target = ctx.text
```
and the echo module would do something similar to detect stickers and images.

@bhsgoclub

**Comment by nmlorg** [comment]
Just to re-summarize, it would be possible to have the bot treat a command sent as a reply to a message in a group chat as if the user had typed the command followed by the replied-to-message's sender's user id at the end of their message. In that case:
```
[user 1234] "Hello there!"
[user 2345] In reply to:
            | Hello there!
            "/command arg1"
```
would be treated like:
```
[user 1234] "Hello there!"
[user 2345] "/command arg1 1234"
```
&nbsp;
This would be the easiest way to move forward. The question left is:&nbsp; **Is it likely there will ever be a command that will want to do something other than treat a command sent as a reply (to a text message) as if the user had typed the message's sender's user id?**

---

Regardless of how text messages are handled, if a user types a command and then sends a sticker or photo, we can just act as if the user had typed the object's id (maybe with a prefix like "sticker:"). That would look something like:
```
[user 2345] "/admin BOTNAME echo NEWCOMMAND"
[user 2345] [sticker AAA3456]
```
being treated as:
```
[user 2345] "/admin BOTNAME echo NEWCOMMAND sticker:AAA3456"
```
&nbsp;
This too would be very easy, so the question is again:&nbsp; **Is it likely there will ever be a command that will want to do something other than treat a sticker/photo sent after a command as if the user had typed the object's id?**

---

If the answers to those are both "no", the final question is:&nbsp; **If a user replies to or forwards a message with a sticker or photo, should the bot treat it as if they had typed the sender's user id, or the object's id, or is it likely there might be two commands that will want to do two different things?**

**Comment by bhsgoclub** [comment]
For record on here my responses to this:

1.) Not that I can foresee at this time. I believe this would be the best option for any command that involves user data. Regardless of it being administrator or utilitiy. 

2.) I can foresee us having a report command in the future where a user could tag a comment or photo for admin review. How would this effect such a feature?

3.) I’m not sure what we would use the object id for. For now let’s just use the senders id and go from there. As stated we could always have a second command in the future if we come across such a need.

**Comment by nmlorg** [comment]
> 2.) I can foresee us having a report command in the future where a user could tag a comment or photo for admin review. How would this effect such a feature?

There would be no reference to the actual message, all that would survive is the object's id. So the bot could show the photo/sticker/whatever to the admin, but wouldn't be able to generate a link back to the original message (or even report who first sent it).

&nbsp;

> 3.) I’m not sure what we would use the object id for. For now let’s just use the senders id and go from there. As stated we could always have a second command in the future if we come across such a need.

Hmm, one thing I can imagine is maybe some kind of /gallery command, where you might do:
```
[user 2345] "/gallery"
[user 2345] [photo 98765]
```
to add a photo to your gallery (in which case it'd be interpreted as `/gallery photo:98765`). It might make sense to also support:
```
[user 2345] [photo 98765]
[user 2345] In reply to:
            | [photo 98765]
            "/gallery"
```
with the expectation that that would also become `/gallery photo:98765`. This would make even more sense as:
```
[user 2345] "/gallery"
[user 2345] Forwarded from user 2345:
            | [photo 98765]
```
becoming `/gallery photo:98765`, so maybe we could get away with treating replies + media as being like forwarded text, but forwards + media as just being media (so the reply would get `/gallery 2345`, but the forward would get `/gallery photo:98765`).

&nbsp;

However, the /report scenario seems to suggest we can't get away with deciding a single policy while decoding the message. That leaves us with:
1. Decide a single policy while decoding the message anyway, seems like:
    * /command + text = /command text
    * /command + media = /command MEDIATYPE:MEDIAID
    * /command + forwarded text = /command USERID
    * /command + forwarded media = /command USERID
    * /command + replied text = /command USERID
    * /command + replied media = /command MEDIATYPE:MEDIAID
2. Include **all** possible metadata, tagged per type, and leave it to command processors to ignore arguments that aren't relevant:
    * /command + text = /command text
    * /command + media = /command MEDIATYPE:MEDIAID
    * /command + forwarded text = /command user:USERID
    * /command + forwarded media = /command user:USERID MEDIATYPE:MEDIAID
    * /command + replied text = /command user:USERID
    * /command + replied media = /command user:USERID MEDIATYPE:MEDIAID
3. Don't try to convert metadata/attachments into text. Leave them attached to the [Context instance](https://github.com/nmlorg/ntelebot/blob/master/ntelebot/preprocess.py#L96) and make the command handlers figure out how to get the relevant data (based on Telegram implementation details).
4. Combining (2) and (3), add separate fields to Context (or a Context.metadata field) to store the processed metadata:
    * /command + text -> `text=`/command text
    * /command + media -> `text=`/command `sticker=`MEDIAID
    * /command + forwarded text -> `text=`/command `forwarded_from=`USERID
    * /command + forwarded media -> `text=`/command `forwarded_from=`USERID `sticker=`MEDIAID
    * /command + replied text -> `text=`/command `reply_from=`USERID
    * /command + replied media -> `text=`/command `reply_from=`USERID `sticker=`MEDIAID

**Comment by nmlorg** [comment]
Okay, so I think it's decided we'll go with (4), which means:
- [ ] Change ntelebot to set `Context.forward_from = USERID` and `Context.text = ''` instead of `Context.text = 'USERID'`, plus setting `Context.reply_from`, `Context.sticker`, and `Context.photo` as appropriate. (Not backwards compatible, so bump major version number.)
- [ ] Change `metabot.modules.admin.admin` to check `Context.forward_from` instead of/in addition to `Context.text`. (It might actually be cleanest to have it be a toggle rather than forwarded message = always add, click button = always remove, if only because right now the bot doesn't store users' usernames/real names, so the buttons are labeled using the human-unfriendly numeric user id.)
- [ ] Change `metabot.modules.echo.admin` to accept a `Context.sticker` or `Context.photo` instead of just relying on a textual message. This can probably still just store the new command as a string, formatted like 'sticker:AAA1234', and have `metabot.modules.echo.echo` check `message` for a prefix of 'sticker:' or 'photo:' and make the appropriate call.
