### ISSUE TITLE
Allow admins to control the day/days of the week to make announcements

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#49]
@realmain would like to be able to do weekly instead of daily announcements (at 8 a.m. every Sunday). I think we can probably add a new field (maybe `dailydaw`) that contains a list/bitfield/whatever of the day or days of week to announce on. (Or alternatively `dailyquietdays` that contains the list/bitfield/whatever of the day or days to **not** announce on, so 0 = every day, 1 = every day except Sunday, 2 = every day except Monday, 3 = every day except Sunday and Monday, etc., though this might end up being less intuitive if/when #48 is implemented.)

**Comment by realmain** [comment]
> Or alternatively dailyquietdays that contains the list/bitfield/whatever of the day or days to not announce on, so 0 = every day, 1 = every day except Sunday, 2 = every day except Monday, 3 = every day except Sunday and Monday, etc.

Should make each day into button toggles for end users to be able to just toggle which days are quiet days.

**Comment by nmlorg** [comment]
Yeah, regardless of how it's recorded, the UI presented to users could probably be two columns of buttons with days of the week that would show if each is enabled or not:

| | |
:-: | :-:
every Sunday | every Monday
every Tuesday | every Wednesday
every Thursday | every Friday
every Saturday | skip all

click "skip all"

| | |
:-: | :-:
not on Sunday | not on Monday
not on Tuesday | not on Wednesday
not on Thursday | not on Friday
not on Saturday | every day

click "not on Sunday"

| | |
:-: | :-:
every Sunday | not on Monday
not on Tuesday | not on Wednesday
not on Thursday | not on Friday
not on Saturday | every day

click "not on Friday"

| | |
:-: | :-:
every Sunday | not on Monday
not on Tuesday | not on Wednesday
not on Thursday | every Friday
not on Saturday | every day

etc.&nbsp; The only issue is if/when we switch from a single "which days and at what time do you want your announcement to be" to a "your first notification is at 8 a.m. every Sunday with calendar A; your second notification is at noon every Wednesday with calendars B and C; your third notification is at ..." style (#48), would one particular UI and/or implementation for the widget now make more sense then; probably not.
